### ISSUE TITLE
Tag semver releases?

### ISSUE THREAD

**Issue by akshayjshah** [HdrHistogram/hdrhistogram-go#27]
Hi! I notice that this project doesn't have any [tagged releases](https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases). Would you mind adding some [SemVer](http://semver.org/)-compatible release tags? It would really, really help those of us using [`dep`](http://github.com/golang/dep) and similar tools.

**Comment by ahothan** [comment]
Added 0.9.0 at the commit where the original codahale repo left off.
We will add 1.0.0 once new features being added will be stable.
Note please do not use the old github URL as it has been transferred to a new home
