### ISSUE TITLE
Return smaller Snapshot

### ISSUE THREAD

**Issue by beberlei** [HdrHistogram/hdrhistogram-go#8]
Would it be possible to return only an array of all counts up to TotalCount? Given a log-normal distribution it is very likely that the high numbers dont have a single count.

That means if you serialize the hdr histogram snapshot as JSON for example you can optimize massively for small snapshots by returning only an array of counts up to the last one that has a positive count.

Since the import already iterates over `countsLen` it could be used to initialize h.counts as well and only the Export() needs an additional loop.

**Comment by tylertreat** [comment]
Yeah, the exporter I wrote is pretty "dumb". This seems like a good optimization and, like you suggest, simple to add. I can put together a PR unless someone beats me to it. :)

**Comment by beberlei** [comment]
@tylertreat I tried my very best but I think the Import code has bugs. The tests never failed even when i commented the loop, not sure what i did wrong.

**Comment by ahothan** [comment]
just scrubbing all issues, and would suggest using the coming encode/decode feature instead of snapshot as it is optimized/compressed
Will close this issue once enocde/decode will be merged unless there is any objection.

**Comment by ahothan** [comment]
Please use the encode/decode feature in stead of snapshot/
